#include <number/rsa.hpp>
#include <number/sha2.hpp>
#include <cassert>
#include <cstdint>
#include <array>

// RSA-1024 uses number<uint32_t, 64> (2048-bit backing for 1024-bit modulus)
using rsa1024_num = number<std::uint32_t, 64>;

// RSA-2048 uses number<uint32_t, 128> (4096-bit backing for 2048-bit modulus)
using rsa2048_num = number<std::uint32_t, 128>;

// --- MGF1 test vector (SHA-256) ---

void test_mgf1() {
    // seed = SHA-256("test") = 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
    // mask_len = 50
    // Expected: e5957dc05e679338528177a1d9f3690c354ca368150dcd13e003b881cb1f902e67394ccaa1bf7584cee55b20ac0a11b335d6
    auto seed = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>("test"), 4));

    auto mask = rsa_detail::mgf1<sha256_state, 64>(seed, 50);

    // Expected: e5957dc05e679338528177a1d9f3690c354ca368150dcd13e003b881cb1f902e
    //           67394ccaa1bf7584cee55b20ac0a11b335d6
    assert(mask[0] == 0xE5 && mask[1] == 0x95 && mask[2] == 0x7D && mask[3] == 0xC0);
    assert(mask[4] == 0x5E && mask[5] == 0x67 && mask[6] == 0x93 && mask[7] == 0x38);
    assert(mask[47] == 0xB3 && mask[48] == 0x35 && mask[49] == 0xD6);
}

// --- RSA-1024 PSS sign/verify roundtrip ---

void test_rsa_pss_roundtrip() {
    // Test key generated by Python (PyCryptodome)
    auto n = *rsa1024_num::from_string(
        "b51ed41adb68167cd17edf321607d47e58e3089587c9ad26e3aa962051cb2758"
        "7d578731fc83bfe14da0c5c99b64daf43ab0d3575d6ff3019b92a253b03b8cdb"
        "5ade3b5d09bbe2cf3c4da42c4db800b96d6e7e2cc826974172cd413a71b18095"
        "bb218e182054ef31fc4c8a4d0507d17ef2b0fd5657eadd2a8bfba001b6a55ad7",
        string_base::hexadecimal);
    auto e = rsa1024_num(65537U);
    auto d = *rsa1024_num::from_string(
        "2e89cad751cc17871fef591b4e04da0952fe971c90e4f5bc59e061add1468188"
        "1fc0c748c548f71b45ae8b53c7bd6cf337476b2e7620475100eff70cc8ea2c41"
        "5bef5753af9e3b9c84771248a3ccb946e15444bd30f7cd9d0fd1a962a55ed370"
        "b395de506b09bfe588144f5ab790b5ca45f5994edaef2778cecc278d4d6f984d",
        string_base::hexadecimal);

    rsa_private_key<rsa1024_num> priv{n, d};
    rsa_public_key<rsa1024_num> pub{n, e};

    // Hash "test message"
    const char* msg = "test message";
    auto mHash = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(msg), 12));

    // Sign with all-zero salt (32 bytes)
    std::array<uint8_t, 32> salt{};
    auto sig = rsa_pss_sign<rsa1024_num, sha256_state>(priv, mHash, salt);

    // Verify
    assert((rsa_pss_verify<rsa1024_num, sha256_state>(pub, mHash, sig)));
}

// --- Verify known PSS signature ---

void test_rsa_pss_known_signature() {
    auto n = *rsa1024_num::from_string(
        "b51ed41adb68167cd17edf321607d47e58e3089587c9ad26e3aa962051cb2758"
        "7d578731fc83bfe14da0c5c99b64daf43ab0d3575d6ff3019b92a253b03b8cdb"
        "5ade3b5d09bbe2cf3c4da42c4db800b96d6e7e2cc826974172cd413a71b18095"
        "bb218e182054ef31fc4c8a4d0507d17ef2b0fd5657eadd2a8bfba001b6a55ad7",
        string_base::hexadecimal);
    auto e = rsa1024_num(65537U);

    rsa_public_key<rsa1024_num> pub{n, e};

    // mHash = SHA-256("test message")
    const char* msg = "test message";
    auto mHash = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(msg), 12));

    // Known signature from Python (salt = 32 zero bytes)
    auto sig_val = *rsa1024_num::from_string(
        "5dcb0e175eb46fc5cfeb88a90a8db0a136f6843a455334c056858fc22e0756fc"
        "1b16e3ed80f74b356ca0fa99bff7ffc8b0963db4a4763ec2324fb76a9828412e"
        "0c541c081ad19b3924522e02da5ffd3063cb83a5992458025cd0f52cea781d48"
        "25b147ce93534358956c5f1e926dfbe8d44a9a1eb11fc0ff04daa67fbece1339",
        string_base::hexadecimal);

    rsa_signature<rsa1024_num> sig{sig_val};
    assert((rsa_pss_verify<rsa1024_num, sha256_state>(pub, mHash, sig)));
}

// --- Wrong message rejected ---

void test_rsa_pss_wrong_message() {
    auto n = *rsa1024_num::from_string(
        "b51ed41adb68167cd17edf321607d47e58e3089587c9ad26e3aa962051cb2758"
        "7d578731fc83bfe14da0c5c99b64daf43ab0d3575d6ff3019b92a253b03b8cdb"
        "5ade3b5d09bbe2cf3c4da42c4db800b96d6e7e2cc826974172cd413a71b18095"
        "bb218e182054ef31fc4c8a4d0507d17ef2b0fd5657eadd2a8bfba001b6a55ad7",
        string_base::hexadecimal);
    auto e = rsa1024_num(65537U);
    auto d = *rsa1024_num::from_string(
        "2e89cad751cc17871fef591b4e04da0952fe971c90e4f5bc59e061add1468188"
        "1fc0c748c548f71b45ae8b53c7bd6cf337476b2e7620475100eff70cc8ea2c41"
        "5bef5753af9e3b9c84771248a3ccb946e15444bd30f7cd9d0fd1a962a55ed370"
        "b395de506b09bfe588144f5ab790b5ca45f5994edaef2778cecc278d4d6f984d",
        string_base::hexadecimal);

    rsa_private_key<rsa1024_num> priv{n, d};
    rsa_public_key<rsa1024_num> pub{n, e};

    const char* msg = "test message";
    auto mHash = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(msg), 12));

    std::array<uint8_t, 32> salt{};
    auto sig = rsa_pss_sign<rsa1024_num, sha256_state>(priv, mHash, salt);

    // Verify with wrong message
    const char* wrong = "wrong message";
    auto wrongHash = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(wrong), 13));
    assert((!rsa_pss_verify<rsa1024_num, sha256_state>(pub, wrongHash, sig)));
}

// --- Corrupted signature rejected ---

void test_rsa_pss_corrupted_signature() {
    auto n = *rsa1024_num::from_string(
        "b51ed41adb68167cd17edf321607d47e58e3089587c9ad26e3aa962051cb2758"
        "7d578731fc83bfe14da0c5c99b64daf43ab0d3575d6ff3019b92a253b03b8cdb"
        "5ade3b5d09bbe2cf3c4da42c4db800b96d6e7e2cc826974172cd413a71b18095"
        "bb218e182054ef31fc4c8a4d0507d17ef2b0fd5657eadd2a8bfba001b6a55ad7",
        string_base::hexadecimal);
    auto e = rsa1024_num(65537U);
    auto d = *rsa1024_num::from_string(
        "2e89cad751cc17871fef591b4e04da0952fe971c90e4f5bc59e061add1468188"
        "1fc0c748c548f71b45ae8b53c7bd6cf337476b2e7620475100eff70cc8ea2c41"
        "5bef5753af9e3b9c84771248a3ccb946e15444bd30f7cd9d0fd1a962a55ed370"
        "b395de506b09bfe588144f5ab790b5ca45f5994edaef2778cecc278d4d6f984d",
        string_base::hexadecimal);

    rsa_private_key<rsa1024_num> priv{n, d};
    rsa_public_key<rsa1024_num> pub{n, e};

    const char* msg = "test message";
    auto mHash = sha256(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(msg), 12));

    std::array<uint8_t, 32> salt{};
    auto sig = rsa_pss_sign<rsa1024_num, sha256_state>(priv, mHash, salt);

    // Corrupt the signature
    rsa_signature<rsa1024_num> bad_sig{sig.value + rsa1024_num(1U)};
    assert((!rsa_pss_verify<rsa1024_num, sha256_state>(pub, mHash, bad_sig)));
}

// --- Message convenience wrappers ---

void test_rsa_pss_message_convenience() {
    auto n = *rsa1024_num::from_string(
        "b51ed41adb68167cd17edf321607d47e58e3089587c9ad26e3aa962051cb2758"
        "7d578731fc83bfe14da0c5c99b64daf43ab0d3575d6ff3019b92a253b03b8cdb"
        "5ade3b5d09bbe2cf3c4da42c4db800b96d6e7e2cc826974172cd413a71b18095"
        "bb218e182054ef31fc4c8a4d0507d17ef2b0fd5657eadd2a8bfba001b6a55ad7",
        string_base::hexadecimal);
    auto e = rsa1024_num(65537U);
    auto d = *rsa1024_num::from_string(
        "2e89cad751cc17871fef591b4e04da0952fe971c90e4f5bc59e061add1468188"
        "1fc0c748c548f71b45ae8b53c7bd6cf337476b2e7620475100eff70cc8ea2c41"
        "5bef5753af9e3b9c84771248a3ccb946e15444bd30f7cd9d0fd1a962a55ed370"
        "b395de506b09bfe588144f5ab790b5ca45f5994edaef2778cecc278d4d6f984d",
        string_base::hexadecimal);

    rsa_private_key<rsa1024_num> priv{n, d};
    rsa_public_key<rsa1024_num> pub{n, e};

    const char* msg = "hello world";
    auto msg_span = std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(msg), 11);

    std::array<uint8_t, 32> salt{};
    auto sig = rsa_pss_sign_message<rsa1024_num, sha256_state>(priv, msg_span, salt);
    assert((rsa_pss_verify_message<rsa1024_num, sha256_state>(pub, msg_span, sig)));
}

int main() {
    test_mgf1();
    test_rsa_pss_roundtrip();
    test_rsa_pss_known_signature();
    test_rsa_pss_wrong_message();
    test_rsa_pss_corrupted_signature();
    test_rsa_pss_message_convenience();
    return 0;
}
