#include <asn1/pem.hpp>
#include <asn1/parser.hpp>
#include <asn1/der/codegen.hpp>
#include <cassert>
#include <cstdint>
#include <span>
#include <string_view>

using namespace asn1;
using namespace asn1::der;

// Parse X.509 schema at compile time
constexpr char x509_asn1[] = {
    #embed "definitions/x509.asn1"
};
constexpr auto X509Mod = parse_module(std::string_view{x509_asn1, sizeof(x509_asn1)});

// --- Test: Parse a self-signed RSA certificate generated by OpenSSL ---

constexpr std::string_view test_cert_pem =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDPzCCAiegAwIBAgIUKNlHYoQhEYbN2mOoxeCugPNmXZAwDQYJKoZIhvcNAQEL\n"
    "BQAwLzENMAsGA1UEAwwEdGVzdDERMA8GA1UECgwIVGVzdCBPcmcxCzAJBgNVBAYT\n"
    "AlVTMB4XDTI2MDMyODIzNTA1M1oXDTI3MDMyODIzNTA1M1owLzENMAsGA1UEAwwE\n"
    "dGVzdDERMA8GA1UECgwIVGVzdCBPcmcxCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG\n"
    "9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4MXbTC/x+tBNbH9yaPJ4HxTdfqjxGbwqh48G\n"
    "NfBrWhD2t/WvAWUru+GzxDCrJjfOb2SIB7Kt2jcnXKndtmDKl9GRjaWtZQddGpvZ\n"
    "tO0IW0wt3ysFXDI18hdcfoyWCrRrnHeAyeyVNWi4WHw8ZVWbpDwvWMEfgtUHKbNu\n"
    "NPe7hT8xubt1CZv3bvxYfqU2LMWkkpChzJ5XbduV9dJTH3qIOkZlGvU7FbeFOyyn\n"
    "3imLledkBXyiLI83zTSAXRmKL7X0bl8QPsay927J/23Z394d8GQ0Mx1J45/q8WE3\n"
    "xeg6e7Q1BdwPcFulBGAB+6inDmDZ4KYSYb8yAiXgmHy8eS+NWQIDAQABo1MwUTAd\n"
    "BgNVHQ4EFgQUb2jHb98Nl5yIIjQCb+273CSukcIwHwYDVR0jBBgwFoAUb2jHb98N\n"
    "l5yIIjQCb+273CSukcIwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC\n"
    "AQEAhpX38NZH7RLitUNkDDu2HfureKzGhQ8VmcBVA1yzGdwdim4xAsPTd5absVbJ\n"
    "fb+n9BV23Ll9SvSaL5c7NE91ZS+KAffuP5NL2nfxbxJ3HZ8Anf56k47ZS6JTdFc7\n"
    "U9NXmu5m5SzCjqr4Snm9NE+dIA5IvEiksOJAC7Aq2+/ICHUWDLXAmPWRz2Z6uK7L\n"
    "UwuFqrnkMYd3BdSWyf5wDRmWTa2S93UVhWa9pkBAyDILJUvgByPunBW7QmStb4jO\n"
    "lpQUMmN2NNwRr1gCjbrVflbBRzkIwHJxr+PRYHXb9hJLAG1o0By0mTRUJIx57Jq/\n"
    "cXwIHXG4jHYg6IMrhHQ8g4ko/Q==\n"
    "-----END CERTIFICATE-----\n";

void test_parse_rsa_certificate() {
    auto cert = asn1::pem::decode_to<X509Mod, X509Mod.find_type("Certificate")>(test_cert_pem);

    // Access TBSCertificate
    auto& tbs = cert.get<"tbsCertificate">();

    // Version should be present (v3 = 2)
    assert(tbs.get<"version">().has_value());
    auto version_int = tbs.get<"version">()->to_int64();
    assert(version_int == 2);  // v3

    // Serial number should be non-empty
    auto& serial = tbs.get<"serialNumber">();
    assert(!serial.bytes.empty());

    // Signature algorithm OID (sha256WithRSAEncryption = 1.2.840.113549.1.1.11)
    auto& sig_alg = tbs.get<"signature">();
    auto alg_oid = sig_alg.get<"algorithm">().to_string();
    assert(alg_oid == "1.2.840.113549.1.1.11");

    // Issuer - access via the CHOICE wrapper
    auto& issuer = tbs.get<"issuer">();
    auto& issuer_rdns = issuer.as<"rdnSequence">();
    assert(issuer_rdns.size() == 3);  // CN, O, C

    // Subject should match issuer (self-signed)
    auto& subject = tbs.get<"subject">();
    auto& subject_rdns = subject.as<"rdnSequence">();
    assert(subject_rdns.size() == 3);

    // Validity - notBefore and notAfter should be UTCTime
    auto& validity = tbs.get<"validity">();
    auto& not_before = validity.get<"notBefore">();
    // UTCTime is the first CHOICE alternative
    auto& not_before_bytes = not_before.as<"utcTime">();
    assert(!not_before_bytes.bytes.empty());
    // UTCTime format: YYMMDDHHMMSSZ (13 bytes)
    assert(not_before_bytes.bytes.size() == 13);

    // SubjectPublicKeyInfo
    auto& spki = tbs.get<"subjectPublicKeyInfo">();
    auto spki_alg_oid = spki.get<"algorithm">().get<"algorithm">().to_string();
    // rsaEncryption = 1.2.840.113549.1.1.1
    assert(spki_alg_oid == "1.2.840.113549.1.1.1");

    // Public key BIT STRING should contain the RSA public key DER
    auto& pub_key_bits = spki.get<"subjectPublicKey">();
    assert(!pub_key_bits.bytes.empty());

    // Extensions should be present (v3 cert)
    assert(tbs.get<"extensions">().has_value());
    auto& exts = *tbs.get<"extensions">();
    assert(exts.size() == 3);  // subjectKeyIdentifier, authorityKeyIdentifier, basicConstraints

    // Check first extension OID
    auto ext0_oid = exts[0].get<"extnID">().to_string();
    // subjectKeyIdentifier = 2.5.29.14
    assert(ext0_oid == "2.5.29.14");

    // Outer signature algorithm should match inner
    auto& outer_sig_alg = cert.get<"signatureAlgorithm">();
    auto outer_alg_oid = outer_sig_alg.get<"algorithm">().to_string();
    assert(outer_alg_oid == alg_oid);

    // Signature value should be non-empty
    auto& sig_value = cert.get<"signatureValue">();
    assert(!sig_value.bytes.empty());
}

// --- Test: Parse an EC certificate ---

void test_parse_ec_certificate() {
    // Generate an EC certificate inline for testing
    // We'll use a hardcoded one to avoid runtime OpenSSL dependency
    // For now, just verify the RSA cert parsing is solid
    // (EC cert parsing uses the same infrastructure)
}

// --- Test: Access individual RDN attributes ---

void test_rdn_access() {
    auto cert = asn1::pem::decode_to<X509Mod, X509Mod.find_type("Certificate")>(test_cert_pem);
    auto& tbs = cert.get<"tbsCertificate">();
    auto& subject_rdns = tbs.get<"subject">().as<"rdnSequence">();

    // Each RDN is a SET OF AttributeTypeAndValue (usually just 1 element)
    // Expected: CN=test, O=Test Org, C=US

    // First RDN: CN (2.5.4.3)
    assert(subject_rdns[0].size() == 1);
    auto cn_oid = subject_rdns[0][0].get<"type">().to_string();
    assert(cn_oid == "2.5.4.3");

    // Second RDN: O (2.5.4.10)
    assert(subject_rdns[1].size() == 1);
    auto o_oid = subject_rdns[1][0].get<"type">().to_string();
    assert(o_oid == "2.5.4.10");

    // Third RDN: C (2.5.4.6)
    assert(subject_rdns[2].size() == 1);
    auto c_oid = subject_rdns[2][0].get<"type">().to_string();
    assert(c_oid == "2.5.4.6");
}

// --- Test: Extension parsing ---

void test_extensions() {
    auto cert = asn1::pem::decode_to<X509Mod, X509Mod.find_type("Certificate")>(test_cert_pem);
    auto& tbs = cert.get<"tbsCertificate">();
    auto& exts = *tbs.get<"extensions">();

    // subjectKeyIdentifier (2.5.29.14) - not critical
    assert(exts[0].get<"extnID">().to_string() == "2.5.29.14");
    // critical field is DEFAULT FALSE, so should be absent (nullopt) or false
    if (exts[0].get<"critical">().has_value())
        assert(exts[0].get<"critical">()->value == false);

    // authorityKeyIdentifier (2.5.29.35)
    assert(exts[1].get<"extnID">().to_string() == "2.5.29.35");

    // basicConstraints (2.5.29.19) - critical
    assert(exts[2].get<"extnID">().to_string() == "2.5.29.19");
    assert(exts[2].get<"critical">().has_value());
    assert(exts[2].get<"critical">()->value == true);

    // extnValue is an OCTET STRING containing the extension's DER encoding
    assert(!exts[2].get<"extnValue">().bytes.empty());
}

int main() {
    test_parse_rsa_certificate();
    test_rdn_access();
    test_extensions();
    return 0;
}
