#include <x509/basic_constraints_verifier.hpp>
#include <x509/key_usage_verifier.hpp>
#include <x509/time_verifier.hpp>
#include <x509/trust_store.hpp>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <ctime>
#include <string_view>
#include <vector>

using namespace asn1::x509;

// --- Test certificates (generated by OpenSSL) ---

// Self-signed RSA-2048/SHA-256 CA certificate
constexpr std::string_view ca_pem =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDPTCCAiWgAwIBAgIUA6fL/MxvYA1LQraAaXdRuWKfMN0wDQYJKoZIhvcNAQEL\n"
    "BQAwLjEQMA4GA1UEAwwHVGVzdCBDQTENMAsGA1UECgwEVGVzdDELMAkGA1UEBhMC\n"
    "VVMwHhcNMjYwMzI5MDAxNzEwWhcNMjcwMzI5MDAxNzEwWjAuMRAwDgYDVQQDDAdU\n"
    "ZXN0IENBMQ0wCwYDVQQKDARUZXN0MQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcN\n"
    "AQEBBQADggEPADCCAQoCggEBAMUmnlPJJ/TeqO6A5+58BarrmdDAJ4S3NDXYi/Kv\n"
    "wgk/PjcH9Puz5uhUTgqtpFBwZ2lU/UL0DyHCPZPGf6M/TI/7Gw1IDBdyF++ksJLB\n"
    "CMfG7bzJ1rXZpiInv8wGwpZRJq3XrV26zcUs3/8f4pvba7t6YUmSbOBOpyAkxq8Z\n"
    "vtsYyAHYBQg7qHrZf09h6NxOdAp5m44h7AOFdJ6n2m4bElBZW0ccfPv3oEDjV1l6\n"
    "I9Y/jc1ymb19NPc2qTMxLt/V93VYoiVGyH0JI69mi+qli/RJXT9XUGbX++nB5t3B\n"
    "3JeeU/tti8p7pEAyt7Ui8tM3U9kJ0drKAuVmFLJgidZDxDMCAwEAAaNTMFEwHQYD\n"
    "VR0OBBYEFKf/otdsL3UZ/KSeZWjun/NLMtRWMB8GA1UdIwQYMBaAFKf/otdsL3UZ\n"
    "/KSeZWjun/NLMtRWMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\n"
    "AJ/FDe0vBwFDaUGSq/koauIQyaHFWrnpMBaX122LYL+c80FzISzbV7xoITrM0MBx\n"
    "vd7MzEKW6L8f//J9gwL/3xcoRSujtbUsIR+J6XhT0TD4z8Nhgc0nW70VzCwd1mIq\n"
    "bbbioE6Hegcg1uBdRK8r42hckaSQlKPqerWKwIR3x95W1RNGxRX2ANuDiP9oIO3E\n"
    "xawiSQW93F77tOiEae+sxUIjfrW5HnBks8wO5u/EAzVGIZVImcqdK0FBj/Bsg930\n"
    "7Ju3SAiBeewLxVxOBq37oROPKWxm1ZmuiN9mI6misUjb5uJSg1fG2aPgFy7HovPu\n"
    "VV4g3phMJhKLMMdl9LX88vc=\n"
    "-----END CERTIFICATE-----\n";

// Leaf certificate signed by the CA above
constexpr std::string_view leaf_pem =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDMjCCAhqgAwIBAgIUMtq3kjYumz0sus9S5n7uMmtmlHYwDQYJKoZIhvcNAQEL\n"
    "BQAwLjEQMA4GA1UEAwwHVGVzdCBDQTENMAsGA1UECgwEVGVzdDELMAkGA1UEBhMC\n"
    "VVMwHhcNMjYwMzI5MDAxNzEwWhcNMjcwMzI5MDAxNzEwWjA0MRYwFAYDVQQDDA1s\n"
    "ZWFmLnRlc3QuY29tMQ0wCwYDVQQKDARUZXN0MQswCQYDVQQGEwJVUzCCASIwDQYJ\n"
    "KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMnvmRKhR8Uy4BtyauKMMnbNUdNbOwz/\n"
    "h6k7mLOKlwJ2S9ZfZG6DSfB5YLNKGYZ2p9InG1gs5LGDrTUt+382golVdIlIwn0g\n"
    "nNO9/cOwJ2Pgp63UFAicvCP/FprzkaZbYYAeqqNacRyGb8/wA2+CMIxFpeCgtWcm\n"
    "zJeK5AUAnHb4HsvOYvdNK78TqlGJSglfIcfJ9gvX6HXt0zI/t9MdfEdsrjxyrp5w\n"
    "jFQ/yc+xL0ZIDPI+GEGPHUqwcm+HOFQHvEE4nVtZw1kMoKhnUMggYDMRyXevKs/f\n"
    "Du4Yw1AUyCkYqwdUdoTYfbuy3O5ZsgOYTouqxfPMyx/tgCC/n/1sr0ECAwEAAaNC\n"
    "MEAwHQYDVR0OBBYEFCq5CG8ACUvNoe2+ZcikEObUA/CLMB8GA1UdIwQYMBaAFKf/\n"
    "otdsL3UZ/KSeZWjun/NLMtRWMA0GCSqGSIb3DQEBCwUAA4IBAQA/3NzbgdKxVueg\n"
    "Fw3+d6pC/HOUInezy8+Z+OKAmA+XsyeEjDyNk9HOzLphOOsx3EREnWHStzNqQ0hn\n"
    "wsGR9rgH6RxIAAB7xfMaM3kM26+SuQ4hJoar0rvGZ9ShPGyJbP7MkMLPxBDVIez+\n"
    "udjAhWO7gx+u9F7sP4/gIZyKDmtt5S5+f1sDSNdPUgcuDmZSo6qIxiL3sKYk8Bzn\n"
    "J2caI5R4id0LpW6ddeaSib7o1UhZKrYDQSOodlF9UFvb8NECSgr5gkOoy3/27x6R\n"
    "GgM0zj9w6eIz1DwL1NXR0/dF0zd8SEzvv/pMaSSruqFTT53oJjB/xAT5bmSRporh\n"
    "BMSMVHTY\n"
    "-----END CERTIFICATE-----\n";

// Self-signed P-256/SHA-256 EC certificate
constexpr std::string_view ec_pem =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBkzCCATmgAwIBAgIUK/0Y3VJJbo9qh2k2HAwis0MwLVAwCgYIKoZIzj0EAwIw\n"
    "HzEQMA4GA1UEAwwHRUMgVGVzdDELMAkGA1UEBhMCVVMwHhcNMjYwMzI5MDAxNzEw\n"
    "WhcNMjcwMzI5MDAxNzEwWjAfMRAwDgYDVQQDDAdFQyBUZXN0MQswCQYDVQQGEwJV\n"
    "UzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFwudXj8GGaBwTI2DBEU2oSAjznt\n"
    "wyWMMxIZgN1i8MBnIpuljrID6uAqhHQW707lht1r3cD1vekq06ANgJK6a72jUzBR\n"
    "MB0GA1UdDgQWBBQskMzYA1SE3aS0zFqFuBrJ0DqV2DAfBgNVHSMEGDAWgBQskMzY\n"
    "A1SE3aS0zFqFuBrJ0DqV2DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gA\n"
    "MEUCIQDU+QpgfxYO36f/gwDLrTjvtdvNHabDvHWzx3f1F33jtgIgS4zMzEVl2guw\n"
    "fw7N8J9X5Prf9VhAI5Fxldd9lnF0Ky4=\n"
    "-----END CERTIFICATE-----\n";

// --- Helpers ---

std::vector<uint8_t> pem_to_der(std::string_view pem) {
    return asn1::pem::decode(pem).der;
}

// --- Tests ---

void test_extract_tbs_der() {
    auto der = pem_to_der(ca_pem);
    auto tbs = extract_tbs_der(der);
    // TBS should be a SEQUENCE (tag 0x30)
    assert(tbs[0] == 0x30);
    // TBS should be shorter than the full certificate
    assert(tbs.size() < der.size());
    // TBS should be a valid DER element (parseable)
    asn1::der::Reader r{tbs};
    auto hdr = r.read_header();
    assert(hdr.tag_number == 0x10);  // SEQUENCE
    assert(hdr.length + hdr.header_size == tbs.size());
}

void test_extract_rsa_public_key() {
    auto cert = parse_certificate_pem(ca_pem);
    auto key = extract_public_key(cert);

    // Should be RSA
    assert(std::holds_alternative<rsa_public_key<rsa_num>>(key));
    auto& rsa = std::get<rsa_public_key<rsa_num>>(key);

    // Public exponent should be 65537
    assert(rsa.e == rsa_num(65537U));

    // Modulus should be 2048 bits
    assert(rsa.n.bit_width() == 2048);
}

void test_extract_ec_public_key() {
    auto cert = parse_certificate_pem(ec_pem);
    auto key = extract_public_key(cert);

    // Should be P-256 point
    assert(std::holds_alternative<point<p256_curve>>(key));
    auto& pt = std::get<point<p256_curve>>(key);

    // Point should be on the curve
    assert(pt.on_curve());
}

void test_self_signed_rsa_verify() {
    auto der = pem_to_der(ca_pem);
    auto cert = parse_certificate(der);
    auto key = extract_public_key(cert);

    // Self-signed: verify with own public key
    assert(verify_certificate_signature(der, cert, key));
}

void test_self_signed_ec_verify() {
    auto der = pem_to_der(ec_pem);
    auto cert = parse_certificate(der);
    auto key = extract_public_key(cert);

    assert(verify_certificate_signature(der, cert, key));
}

void test_ca_signs_leaf() {
    auto ca_der = pem_to_der(ca_pem);
    auto leaf_der = pem_to_der(leaf_pem);

    auto ca_cert = parse_certificate(ca_der);
    auto leaf_cert = parse_certificate(leaf_der);

    auto ca_key = extract_public_key(ca_cert);

    // Leaf should verify against CA's key
    assert(verify_certificate_signature(leaf_der, leaf_cert, ca_key));
}

void test_wrong_key_rejected() {
    auto ca_der = pem_to_der(ca_pem);
    auto ec_der = pem_to_der(ec_pem);

    auto ca_cert = parse_certificate(ca_der);
    auto ec_cert = parse_certificate(ec_der);

    // Use EC key to verify RSA cert — should fail
    auto ec_key = extract_public_key(ec_cert);
    assert(!verify_certificate_signature(ca_der, ca_cert, ec_key));
}

void test_corrupted_signature_rejected() {
    auto der = pem_to_der(ca_pem);
    auto cert = parse_certificate(der);
    auto key = extract_public_key(cert);

    // Corrupt a byte in the signature area (near the end of the DER)
    auto bad_der = std::vector<uint8_t>(der.begin(), der.end());
    bad_der[bad_der.size() - 10] ^= 0x01;

    auto bad_cert = parse_certificate(bad_der);
    assert(!verify_certificate_signature(bad_der, bad_cert, key));
}

void test_trust_store() {
    trust_store store;
    store.add_pem(ca_pem);

    // Leaf cert's issuer should match CA's subject
    auto leaf_cert = parse_certificate_pem(leaf_pem);
    auto result = store.find_issuer(leaf_cert);
    assert(result.has_value());

    // EC cert's issuer should NOT match CA
    auto ec_cert = parse_certificate_pem(ec_pem);
    auto no_result = store.find_issuer(ec_cert);
    assert(!no_result.has_value());
}

void test_chain_verification() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};
    assert(verify_chain(chain, store));
}

void test_chain_untrusted_root_rejected() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store empty_store;  // no roots

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};
    assert(!verify_chain(chain, empty_store));
}

// --- Custom verifier tests ---

struct always_pass_verifier {
    bool verify(const cert_context&) const { return true; }
};

struct depth_limit_verifier {
    size_t max_depth;
    bool verify(const cert_context& ctx) const {
        return ctx.depth <= max_depth;
    }
};

void test_custom_verifier() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Always-pass verifier: chain should succeed
    assert(verify_chain(chain, store, always_pass_verifier{}));

    // Depth limit 0: leaf resolves directly to trust store at depth 0
    assert(verify_chain(chain, store, depth_limit_verifier{0}));

    // Depth limit 1: also passes
    assert(verify_chain(chain, store, depth_limit_verifier{1}));
}

void test_multiple_verifiers() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Two passing verifiers: should pass
    assert(verify_chain(chain, store, always_pass_verifier{}, depth_limit_verifier{5}));

    // Two passing verifiers with depth 0: leaf resolves directly to trust store
    assert(verify_chain(chain, store, always_pass_verifier{}, depth_limit_verifier{0}));
}

// --- Time verifier tests ---

// Helper: create a time_point from year/month/day
std::chrono::system_clock::time_point make_time(int year, int month, int day) {
    std::tm tm{};
    tm.tm_year = year - 1900;
    tm.tm_mon = month - 1;
    tm.tm_mday = day;
    tm.tm_hour = 12;
    tm.tm_isdst = 0;
    return std::chrono::system_clock::from_time_t(timegm(&tm));
}

void test_time_verifier_valid() {
    // Test certs are valid 2026-03-29 to 2027-03-29
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Check at a time within validity range
    time_verifier tv{make_time(2026, 6, 15)};
    assert(verify_chain(chain, store, tv));
}

void test_time_verifier_expired() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Check at a time after expiry
    time_verifier tv{make_time(2028, 1, 1)};
    assert(!verify_chain(chain, store, tv));
}

void test_time_verifier_not_yet_valid() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Check at a time before notBefore
    time_verifier tv{make_time(2025, 1, 1)};
    assert(!verify_chain(chain, store, tv));
}

void test_time_verifier_system_time() {
    // Certs valid until 2027-03-29, system time should be within range
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Default: uses system_clock::now()
    time_verifier tv{};
    assert(verify_chain(chain, store, tv));
}

void test_time_parse_standalone() {
    // Verify time parsing directly on a parsed certificate
    auto cert = parse_certificate_pem(ca_pem);
    auto& validity = cert.get<"tbsCertificate">().get<"validity">();

    auto not_before = detail::parse_x509_time(validity.get<"notBefore">());
    auto not_after  = detail::parse_x509_time(validity.get<"notAfter">());

    // notAfter must be after notBefore
    assert(not_after > not_before);

    // Check that a known date falls between them
    auto mid = make_time(2026, 6, 15);
    assert(not_before <= mid && mid <= not_after);

    // Check that a date before notBefore is outside
    auto early = make_time(2020, 1, 1);
    assert(early < not_before);
}

// --- Key usage verifier tests ---

void test_key_usage_verifier_no_extension() {
    // CA cert and leaf cert don't have KeyUsage extension
    // Verifier should pass (extension absent = no restriction)
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};
    key_usage_verifier kuv{};
    assert(verify_chain(chain, store, kuv));
}

void test_key_usage_bit_testing() {
    // Test the bit testing helper directly
    asn1::der::BitString bs;
    bs.bytes = {0x06};  // bits: 00000110 → bits 5 and 6 set (keyCertSign, cRLSign)
    bs.unused_bits = 1;

    assert(!detail::has_key_usage_bit(bs, key_usage_bit::digital_signature));  // bit 0
    assert(!detail::has_key_usage_bit(bs, key_usage_bit::key_agreement));      // bit 4
    assert(detail::has_key_usage_bit(bs, key_usage_bit::key_cert_sign));       // bit 5
    assert(detail::has_key_usage_bit(bs, key_usage_bit::crl_sign));            // bit 6
}

void test_key_usage_verifier_direct() {
    // Test verifier directly with a cert_context at different depths
    auto ca_der_vec = pem_to_der(ca_pem);
    auto ca_cert = parse_certificate(ca_der_vec);
    auto tbs_der = extract_tbs_der(ca_der_vec);

    cert_context ctx{
        .cert = ca_cert,
        .issuer = nullptr,
        .cert_der = ca_der_vec,
        .tbs_der = tbs_der,
        .depth = 1,
        .chain_length = 2
    };

    // CA cert has no KeyUsage extension → passes at any depth
    key_usage_verifier kuv{};
    assert(kuv.verify(ctx));
}

// --- Basic constraints verifier tests ---

void test_basic_constraints_ca_at_depth() {
    // CA cert has basicConstraints cA=TRUE
    auto ca_der_vec = pem_to_der(ca_pem);
    auto ca_cert = parse_certificate(ca_der_vec);
    auto tbs_der = extract_tbs_der(ca_der_vec);

    cert_context ctx{
        .cert = ca_cert,
        .issuer = nullptr,
        .cert_der = ca_der_vec,
        .tbs_der = tbs_der,
        .depth = 1,
        .chain_length = 2
    };

    basic_constraints_verifier bcv{};
    assert(bcv.verify(ctx));
}

void test_basic_constraints_leaf_no_constraint() {
    // Leaf cert has no basicConstraints — should pass at depth 0
    auto leaf_der_vec = pem_to_der(leaf_pem);
    auto leaf_cert = parse_certificate(leaf_der_vec);
    auto tbs_der = extract_tbs_der(leaf_der_vec);

    cert_context ctx{
        .cert = leaf_cert,
        .issuer = nullptr,
        .cert_der = leaf_der_vec,
        .tbs_der = tbs_der,
        .depth = 0,
        .chain_length = 2
    };

    basic_constraints_verifier bcv{};
    assert(bcv.verify(ctx));
}

void test_basic_constraints_missing_on_intermediate() {
    // Leaf cert does NOT have basicConstraints — should FAIL at depth > 0
    auto leaf_der_vec = pem_to_der(leaf_pem);
    auto leaf_cert = parse_certificate(leaf_der_vec);
    auto tbs_der = extract_tbs_der(leaf_der_vec);

    cert_context ctx{
        .cert = leaf_cert,
        .issuer = nullptr,
        .cert_der = leaf_der_vec,
        .tbs_der = tbs_der,
        .depth = 1,  // pretend it's an intermediate
        .chain_length = 3
    };

    basic_constraints_verifier bcv{};
    assert(!bcv.verify(ctx));
}

void test_basic_constraints_parse() {
    // Verify BasicConstraints parsing on the CA cert directly
    auto ca_cert = parse_certificate_pem(ca_pem);
    auto bc = detail::parse_basic_constraints(ca_cert);
    assert(bc.has_value());
    assert(bc->ca == true);
    // Our test CA cert doesn't have pathLenConstraint
    assert(!bc->path_len_constraint.has_value());
}

void test_basic_constraints_chain() {
    // Full chain verification with basic_constraints_verifier
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};
    basic_constraints_verifier bcv{};
    assert(verify_chain(chain, store, bcv));
}

// --- Integration: all verifiers together ---

void test_all_verifiers_together() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    time_verifier tv{make_time(2026, 6, 15)};
    key_usage_verifier kuv{};
    basic_constraints_verifier bcv{};

    assert(verify_chain(chain, store, tv, kuv, bcv));
}

void test_all_verifiers_expired_fails() {
    auto leaf_der = pem_to_der(leaf_pem);
    auto ca_der = pem_to_der(ca_pem);

    trust_store store;
    store.add_pem(ca_pem);

    std::vector<std::vector<uint8_t>> chain = {leaf_der, ca_der};

    // Expired time should cause failure even with other verifiers passing
    time_verifier tv{make_time(2028, 1, 1)};
    key_usage_verifier kuv{};
    basic_constraints_verifier bcv{};

    assert(!verify_chain(chain, store, tv, kuv, bcv));
}

int main() {
    test_extract_tbs_der();
    test_extract_rsa_public_key();
    test_extract_ec_public_key();
    test_self_signed_rsa_verify();
    test_self_signed_ec_verify();
    test_ca_signs_leaf();
    test_wrong_key_rejected();
    test_corrupted_signature_rejected();
    test_trust_store();
    test_chain_verification();
    test_chain_untrusted_root_rejected();
    test_custom_verifier();
    test_multiple_verifiers();

    // Time verifier
    test_time_verifier_valid();
    test_time_verifier_expired();
    test_time_verifier_not_yet_valid();
    test_time_verifier_system_time();
    test_time_parse_standalone();

    // Key usage verifier
    test_key_usage_verifier_no_extension();
    test_key_usage_bit_testing();
    test_key_usage_verifier_direct();

    // Basic constraints verifier
    test_basic_constraints_ca_at_depth();
    test_basic_constraints_leaf_no_constraint();
    test_basic_constraints_missing_on_intermediate();
    test_basic_constraints_parse();
    test_basic_constraints_chain();

    // Integration
    test_all_verifiers_together();
    test_all_verifiers_expired_fails();

    return 0;
}
